name: CI

on: [push]

jobs:
  posix-build-on-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: posix
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libgtk-3-dev libsqlite3-dev libxml2-dev unzip uuid-dev zlib1g-dev
      - run: make -s download
      - run: make -s external
      - run: make -s all
      - run: make check
  xcode-build-on-macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: xcode
    env:
      LIBTOOL: glibtool
      LIBTOOLIZE: glibtoolize
    steps:
      - uses: actions/checkout@v2
      - run: brew install pkg-config
      - run: cp config.mk.travis config.mk
      - run: make -s download
      - run: make -s external
      - run: make -s all
      - run: make check
